### ISSUE TITLE
Add. 17,217, fol. 63 | https://bl.vuexistapps.us/manuscript/955 (Part27)

### ISSUE THREAD

**Issue by Erfan-Syriaca** [srophe/britishLibrary-data#1120]
### Problems with Manuscript Overview

- Since the colophon is not that legible, Wright records the date as "A.D. 6.. / A. Gr. 9.." which appears in the same way in the MS overview. Perhaps it should be paraphrased. 
- No script is mentioned in the MS overview. It should be Unspecified Syriac script, multiple hands. 

### Categories of Manuscript Overview Problems

- [ ] Whitespace
- [ ] Typo(s)
- [X] Incorrect content
- [X] Missing content

### Problems with Physical Description

- The Hands section is missing. Beside the colophon, which may be considered Hand 1, the writing on the verso, as Wright describes, is of a later hand, and so, should be considered Hand 2 (Addition 2).

### Categories of Physical Description Problems

- [ ] Whitespace
- [ ] Typo(s)
- [ ] Incorrect content
- [X] Missing content

**Comment by mikey-tang16** [comment]
Resolved
- hand 1 added:  Very little of the writing is legible.
- hand 2 added: see additions

Questions:
- Should we paraphrase the date/century? A.D. 6.. / A. Gr. 9.. as A.D. 7th, etc
- should I add date to hand 1?
@wlpotter

**Comment by wlpotter** [comment]
Yes, let's add the date to hand 1. 

Let's leave the date as-is; we have the normalized ISO date attributes giving the full range of 600-699, so it will still show up in date searches correctly. This date format indicates that the ms is securely dated via colophon, even if only partially, compared with dates like "7th century" which indicate it is based on estimates from paleography

**Comment by mikey-tang16** [comment]
Just to double check: The following is ok for adding date to handnote?
 Hand 1: Very little of the writing is legible, of the {date notBefore-iso="0600" notAfter-iso="0699"} 7th century /date.

**Comment by wlpotter** [comment]
Yes that sounds fine to me
